Added regex checks for 'Link to Work' and 'Link to Creator Profile'
creativecommons/chooser pull request #456
Opened 2023-03-08 07:45 UTC by soustab10

## Fixes

Fixes #452  by @soustab10 (myself)

## Description
- This PR adds regex checks for the 'Link to Work' and 'Link to Creator Profile' fields under Attribution details section.
- It adds a numeric validation for the year of creation to be a 4 digit number.

## Tests
This PR can be tested by putting an invalid URL to the mentioned sections. A prompt `Please enter a valid URL` is presented.

## Screenshots

![image](https://user-images.githubusercontent.com/95632583/223651869-3c65d3f2-d42d-4980-9741-1c33ad799101.png)

Leaving the field empty or putting the correct URL gives no error.

![image](https://user-images.githubusercontent.com/95632583/223652093-a7f3b314-3acd-46dc-8ccc-6e9066296649.png)

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

2023-03-08 07:45 UTC, soustab10 commented
@possumbilities please review this PR. Thank you.

2023-03-10 20:08 UTC, possumbilities commented
@soustab10 Thanks for working on this! I see you used a new dependency `vee-validate`. This project already needs some pairing back on how many dependencies its utilizing. So I'm going to look into it further. The preference here would be accomplishing validation without introducing new dependencies into the chain first, and then IF it's necessary outlining why, what the cost/benefit analysis is, etc.

2023-03-10 20:12 UTC, soustab10 commented
> @soustab10 Thanks for working on this! I see you used a new dependency `vee-validate`. This project already needs some pairing back on how many dependencies its utilizing. So I'm going to look into it further. The preference here would be accomplishing validation without introducing new dependencies into the chain first, and then IF it's necessary outlining why, what the cost/benefit analysis is, etc.

@possumbilities vee-validate isn't necessary at all. I was just trying during the development phase to see what works best. I will commit soon with the necessary changes. Thank you.

2023-03-21 20:27 UTC, possumbilities commented
@soustab10 It looks like your project isn't passing the checks, can you investigate and verify?

2023-03-21 20:29 UTC, soustab10 commented
> @soustab10 It looks like your project isn't passing the checks, can you investigate and verify?

yes, absolutely.

2023-03-21 20:36 UTC, soustab10 commented
@possumbilities the module `@creativecommons/cc-assets` is being read as undefined, causing the build to fail. I am trying to fix this asap.

2023-03-21 20:36 UTC, Cronus1007 commented
@soustab10 It looks like your npm install is failing in the pipelines.

2023-03-21 21:01 UTC, Cronus1007 commented
@soustab10 Can't we completely rid of the vee-validate dependency?

2023-03-22 13:58 UTC, codewithmide commented
> @soustab10 Can't we completely rid of the vee-validate dependency?

@soustab10 do you mind if work this out together?

2023-03-23 07:25 UTC, soustab10 commented
@Cronus1007 I have removed the vee-validate dependency completely.

2023-03-23 08:02 UTC, Cronus1007 commented
@soustab10 Please revert the changes made in package-lock.json. The workflows are still failing. Please have a look upon them as well.

2023-03-23 08:05 UTC, Cronus1007 requested changes

2023-03-23 08:05 UTC, Cronus1007 commented on src/store/index.js
> +
@soustab10 Remove this space please.

2023-03-23 10:51 UTC, soustab10 commented on src/components/AttributionDetailsStep.vue
> +      else if (/[(http(s)?):(www)?a-zA-Z0-9@:%._~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_+.~#?&//=]*)/.test(value)) {
Doing the necessary changes.

2023-03-23 11:11 UTC, soustab10 commented on src/components/AttributionDetailsStep.vue
> +      else if (/[(http(s)?):(www)?a-zA-Z0-9@:%._~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_+.~#?&//=]*)/.test(value)) {
Done. Check it once please.

2023-03-23 13:04 UTC, Cronus1007 commented
@soustab10 Let me make a local run of you PR since your each and every commit is failing with GithubWorkflows.

2023-03-23 13:27 UTC, Cronus1007 commented
@soustab10 I just used the package-lock.json that is into the `main` branch of Chooser codebase.

2023-03-23 13:30 UTC, Cronus1007 commented
Lets wait for @possumbilities to review the PR as well.

2023-03-23 14:18 UTC, Cronus1007 commented
@possumbilities While testing this PR. I was wondering what range should be there for year of creation column since we are able to access any number whose length should be 4 either 1000 or 2029. One thing I would like to highlight in this work is that 0000 is not valid.

2023-03-31 20:37 UTC, possumbilities commented
@Cronus1007 I think there's value in keeping the `package-lock.json` file tracked so we can make changes to it in the future, but people should be careful not committing changes to it when not needed. It does have its uses and I'm not sure its worth removing outright going forward.

2023-03-31 20:39 UTC, possumbilities commented
@soustab10 looks like there's still changes requested pending?

2023-03-31 20:44 UTC, soustab10 commented
> @soustab10 looks like there's still changes requested pending?

I have made the changes requested via this [commit](https://github.com/creativecommons/chooser/pull/456/commits/5d73a6191a8e61bf28254be0fd846a2bd602fbe2)

2023-03-31 20:46 UTC, possumbilities commented
@Cronus1007 it's waiting on you to sign off on the review request I think.

2023-03-31 21:26 UTC, Cronus1007 commented
> @Cronus1007 I think there's value in keeping the `package-lock.json` file tracked so we can make changes to it in the future, but people should be careful not committing changes to it when not needed. 

Makes sense.

2023-04-01 20:35 UTC, Cronus1007 approved these changes
@soustab10 Thanks for the contribution :100: 
@possumbilities LGTM

2023-04-01 20:58 UTC, soustab10 commented
> @soustab10 Thanks for the contribution 💯 @possumbilities LGTM

Thanks a lot! Hoping to make more contributions!

2023-06-23 19:45 UTC, possumbilities commented
Hi! @soustab10 thank you so much for all your work on this, it's greatly appreciated. Apologies for the lengthy delay in response here.

I tested this and there's still at least one unresolved issued with the regex. The URL check seems to be capping the validation of the domain extension to 6characters. As a result valid TLDs will throw an "invalid URL" UX error.

For example:

`https://something.channel`

There's a lengthy list of valid domains that over the 6 character limit in the [IANA list](https://www.iana.org/domains/root/db).

I'd suggest adjusting the regex in the checker to not be bound by the 6character limit on the extension, so the error doesn't throw incorrectly.

2023-07-11 19:26 UTC, possumbilities commented
Hi again @soustab10 just letting you know there's still a minor error here that needs resolving before it can be approved. Thanks so much for all your work so far!

2024-09-30 20:51 UTC, possumbilities commented
Closing as incomplete work

2024-09-30 20:51 UTC, closed without merging